 get http://localhost:3000/todos/?priority=HIGH

###

 get http://localhost:3000/todos/1/

 ###

 get http://localhost:3000/agenda/?date=2021-01-12

 ### 

 post http://localhost:3000/todos/
 Content-Type: Application/json

 {
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

put http://localhost:3000/todos/6/
Content-Type: Application/json

{
  "dueDate": "2021-0-12"
}

###

delete http://localhost:3000/todos/6/